### ISSUE TITLE
'string'->toUpper() example in README.md

### ISSUE THREAD

**Issue by adamcameron** [tpunt/PHP7-Reference#8]
Unless I am mistaken (which is entirely likely) strings aren't objects in PHP, so one cannot call methods on them, let along calling method on literal strings.

The changes to the parser might allow this to work _if strings were objects_, but they aren't so it doesn't.

I actually can't think of a literal->method() call which would work in PHP?

(an otherwise great doc btw, which I refer to constantly during my testing)

**Comment by tpunt** [comment]
Correct - strings aren't objects and as such methods cannot be invoked on them. The changes to the variable syntax, however, now gives the parser the capability to dereference scalars - this just hasn't been fully exploited yet (like being able to invoke methods on string literals).

Other scalars can be (somewhat uselessly) dereferenced though:

``` PHP
echo [1, 2, 3][1]; // 2
```

I may make a note of this in the article though since it has been brought up a couple of times now. Thanks for the feedback!

**Comment by adamcameron** [comment]
Well if you wanted a string example, how about:

```
echo 'abc'[1]; // b
```

?

(granted, it's still not useful ;-)

**Comment by tpunt** [comment]
Yep, that would also work. I think I'll just remove the scalar dereferencing example though, since I can't think of anything useful to show with them :)
